import { forwardRef } from 'react'
import { ACTION_STATUS_BY_KEY, bodyPartLabel } from '../lib/constants'
import { BodyMapStatic } from './BodyMap'

const fmt = (v) => (v == null || v === '' ? '—' : v)
const personLine = (p) =>
  p.kind === 'internal'
    ? `${p.name || 'Unnamed'}${p.dept ? ` (${p.dept})` : ''} · Internal`
    : `${p.name || 'Unnamed'}${p.company ? `, ${p.company}` : ''}${p.contact ? ` · ${p.contact}` : ''} · External`

function Section({ title, children }) {
  return (
    <section className="print-block doc-section">
      <h2 className="doc-section-title">{title}</h2>
      {children}
    </section>
  )
}
function Field({ label, value }) {
  return <div className="mb-1.5"><span className="text-[11px] font-bold uppercase tracking-wide text-ink-500">{label}: </span><span className="text-sm text-ink-900">{fmt(value)}</span></div>
}

/** Printable occupational-illness report. */
const IllnessReportDoc = forwardRef(function IllnessReportDoc({ illness, org }, ref) {
  if (!illness) return <div ref={ref} />
  return (
    <div ref={ref} className="doc-sheet mx-auto max-w-[800px] p-8">
      <div className="doc-header">
        <div>
          <p className="doc-kicker">WEHS · Incident IRA</p>
          <h1 className="doc-title">Occupational illness report</h1>
          <p className="mt-1 text-sm text-ink-500">{org?.name || 'Organization'}</p>
        </div>
        <div className="doc-meta">
          <div><b>{illness.refNo}</b></div>
          <div className="mt-1">Generated {new Date().toLocaleDateString()}</div>
        </div>
      </div>

      <Section title="Exposure Details">
        <div className="grid grid-cols-2 gap-x-8">
          <Field label="Date" value={illness.date} />
          <Field label="Time" value={illness.time} />
          <Field label="Location" value={illness.location} />
          <Field label="Site" value={illness.site} />
          <Field label="Exposed to agent" value={illness.exposedToAgent} />
          <Field label="Duration of exposure" value={illness.exposureDuration} />
          <Field label="PPE in use" value={(illness.ppe || []).join(', ')} />
        </div>
      </Section>

      <Section title="Affected People">
        {(illness.affectedPersonnel || []).length === 0 ? <p className="text-sm text-ink-400">None recorded.</p> : (
          <ul className="list-disc pl-5 text-sm">{illness.affectedPersonnel.map((p) => <li key={p.id}>{personLine(p)}</li>)}</ul>
        )}
      </Section>

      <Section title="Health Issue Triggered">
        <p className="whitespace-pre-wrap text-sm leading-relaxed">{fmt(illness.healthIssue)}</p>
      </Section>

      <Section title="Affected Body Parts">
        <p className="text-sm">{(illness.affectedBodyParts || []).map(bodyPartLabel).join(', ') || '—'}</p>
        {(illness.affectedBodyParts || []).length > 0 && <BodyMapStatic parts={illness.affectedBodyParts} />}
      </Section>

      <Section title="Corrective Actions">
        {(illness.actions || []).length === 0 ? <p className="text-sm text-ink-400">No actions recorded.</p> : (
          <table className="w-full border-collapse text-sm">
            <thead><tr className="border-b border-ink-200 text-left text-[11px] uppercase tracking-wide text-ink-500"><th className="py-1 pr-2">Action</th><th className="py-1 pr-2">Owner</th><th className="py-1 pr-2">Due</th><th className="py-1">Status</th></tr></thead>
            <tbody>
              {illness.actions.map((a) => (
                <tr key={a.id} className="border-b border-ink-100 align-top">
                  <td className="py-1 pr-2">{a.description}</td><td className="py-1 pr-2">{a.ownerName}</td><td className="py-1 pr-2">{a.dueDate}</td><td className="py-1">{ACTION_STATUS_BY_KEY[a.status]?.label || a.status}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Section>

      <p className="doc-foot">
        Generated by Incident IRA. A record-keeping aid; it does not replace any statutory occupational-health reporting obligation.
      </p>
    </div>
  )
})

export default IllnessReportDoc
