// ─────────────────────────────────────────────────────────────────────────────
// ISO 45001:2018 clause knowledge base, correlated to WEHS modules.
// Summaries are short PARAPHRASES of each clause's intent (the standard's text
// is copyrighted and is never reproduced here).
// ─────────────────────────────────────────────────────────────────────────────

export const ISO_CLAUSES = [
  {
    clause: '4.1', title: 'Understanding the organization and its context',
    summary: 'Identify the internal and external issues that affect your OH&S outcomes.',
    modules: [{ label: 'Org Settings', path: '/settings' }],
    keywords: ['context', 'internal issues', 'external issues'],
    stat: null,
  },
  {
    clause: '4.2', title: 'Needs and expectations of workers & interested parties',
    summary: 'Work out who your interested parties are (especially workers) and which of their needs become compliance obligations.',
    modules: [{ label: 'Org Settings', path: '/settings' }, { label: 'Employees', path: '/users' }],
    keywords: ['interested parties', 'stakeholders', 'needs', 'expectations'],
    stat: 'users',
  },
  {
    clause: '4.3', title: 'Scope of the OH&S management system',
    summary: 'Define the boundaries of the management system — activities, locations and what it applies to.',
    modules: [{ label: 'Org Settings (activities & scope granularity)', path: '/settings' }, { label: 'Sites', path: '/sites' }],
    keywords: ['scope', 'boundaries', 'activities', 'locations'],
    stat: 'sites',
  },
  {
    clause: '4.4', title: 'OH&S management system',
    summary: 'Establish, implement, maintain and continually improve the management system and its processes.',
    modules: [{ label: 'WEHS Portal — all modules', path: '/portal' }],
    keywords: ['management system', 'ohsms', 'processes'],
    stat: null,
  },
  {
    clause: '5.1', title: 'Leadership and commitment',
    summary: 'Top management takes overall responsibility for worker protection and leads the OH&S culture.',
    modules: [{ label: 'Dashboards', path: '/dashboard' }],
    keywords: ['leadership', 'commitment', 'top management', 'culture'],
    stat: null,
  },
  {
    clause: '5.2', title: 'OH&S policy',
    summary: 'Maintain a documented OH&S policy with commitments to safe conditions, legal compliance, consultation and continual improvement.',
    modules: [{ label: 'Documents & SDS', path: '/documents' }],
    keywords: ['policy'],
    stat: 'documents',
  },
  {
    clause: '5.3', title: 'Organizational roles, responsibilities and authorities',
    summary: 'Assign and communicate who is responsible and accountable for each part of the system.',
    modules: [{ label: 'Employees (roles, permissions & site access)', path: '/users' }],
    keywords: ['roles', 'responsibilities', 'authorities', 'accountability', 'permissions'],
    stat: 'users',
  },
  {
    clause: '5.4', title: 'Consultation and participation of workers',
    summary: 'Provide processes for consulting workers and enabling their participation in OH&S decisions — committees are the classic mechanism.',
    modules: [{ label: 'HSE Committee', path: '/committee' }],
    keywords: ['consultation', 'participation', 'committee', 'meeting', 'workers voice'],
    stat: 'consultations',
  },
  {
    clause: '6.1.1', title: 'Actions to address risks and opportunities — general',
    summary: 'Plan the system with your context, hazards, risks and legal requirements in mind.',
    modules: [{ label: 'Risk Assessment (HIRA)', path: '/hira' }],
    keywords: ['risks and opportunities', 'planning'],
    stat: 'assessments',
  },
  {
    clause: '6.1.2', title: 'Hazard identification and assessment of risks',
    summary: 'Continually identify hazards and assess OH&S risks (and opportunities) using defined methods and criteria.',
    modules: [{ label: 'Risk Assessment (HIRA) — baseline & site RAs, risk matrix', path: '/hira' }],
    keywords: ['hazard', 'hazard identification', 'risk assessment', 'hira', 'risk matrix', 'baseline'],
    stat: 'assessments',
  },
  {
    clause: '6.1.3', title: 'Legal and other requirements',
    summary: 'Determine, access and keep up to date the legal and other requirements that apply to you.',
    modules: [{ label: 'Documents & SDS', path: '/documents' }],
    keywords: ['legal', 'compliance obligations', 'regulations'],
    stat: null,
  },
  {
    clause: '6.1.4', title: 'Planning action',
    summary: 'Plan actions for risks, legal requirements and emergencies — and track them to completion.',
    modules: [{ label: 'Action Tracker', path: '/actions' }],
    keywords: ['planning action', 'action plan'],
    stat: null,
  },
  {
    clause: '6.2', title: 'OH&S objectives and planning to achieve them',
    summary: 'Set measurable OH&S objectives and plan who does what, by when, with what resources.',
    modules: [{ label: 'Dashboards', path: '/dashboard' }, { label: 'Action Tracker', path: '/actions' }],
    keywords: ['objectives', 'targets', 'kpi'],
    stat: null,
  },
  {
    clause: '7.2', title: 'Competence',
    summary: 'Make sure workers are competent for work that affects OH&S — training, certification and evidence of it.',
    modules: [{ label: 'Training (courses, assignments, matrix, certificates)', path: '/training' }],
    keywords: ['competence', 'training', 'certification', 'course', 'skills', 'lms'],
    stat: 'training',
  },
  {
    clause: '7.3', title: 'Awareness',
    summary: 'Workers must be aware of the policy, hazards relevant to them, and their contribution to the system.',
    modules: [{ label: 'Training — My Learning', path: '/training/my' }],
    keywords: ['awareness', 'induction'],
    stat: 'training',
  },
  {
    clause: '7.4', title: 'Communication',
    summary: 'Decide what to communicate on OH&S, when, to whom and how — internally and externally.',
    modules: [{ label: 'HSE Committee', path: '/committee' }],
    keywords: ['communication', 'communicate'],
    stat: 'consultations',
  },
  {
    clause: '7.5', title: 'Documented information',
    summary: 'Create, update and control the documents and records the system needs.',
    modules: [{ label: 'Documents & SDS (versioned)', path: '/documents' }],
    keywords: ['documented information', 'documents', 'records', 'sds', 'document control'],
    stat: 'documents',
  },
  {
    clause: '8.1.1', title: 'Operational planning and control — general',
    summary: 'Establish criteria and controls for processes so work is carried out safely.',
    modules: [{ label: 'Inspections', path: '/inspections' }, { label: 'Permit to Work', path: '/permits' }],
    keywords: ['operational control', 'operations'],
    stat: 'inspections',
  },
  {
    clause: '8.1.2', title: 'Eliminating hazards and reducing OH&S risks',
    summary: 'Apply the hierarchy of controls: eliminate, substitute, engineer, administrate, then PPE.',
    modules: [{ label: 'Risk Assessment — hierarchy of controls', path: '/hira' }, { label: 'Lockout / Tagout', path: '/loto' }],
    keywords: ['hierarchy of controls', 'eliminate', 'substitution', 'ppe', 'engineering controls', 'loto', 'lockout', 'tagout', 'isolation'],
    stat: 'loto',
  },
  {
    clause: '8.1.3', title: 'Management of change',
    summary: 'Control planned temporary and permanent changes that impact OH&S before they happen.',
    modules: [{ label: 'HSE Committee — Management of Change meetings', path: '/committee' }],
    keywords: ['management of change', 'moc', 'change management'],
    stat: 'consultations',
  },
  {
    clause: '8.1.4', title: 'Procurement (incl. contractors & outsourcing)',
    summary: 'Control procured goods/services and coordinate hazards with contractors and outsourced processes.',
    modules: [{ label: 'Permit to Work (contractor control)', path: '/permits' }],
    keywords: ['procurement', 'contractor', 'outsourcing', 'permit'],
    stat: 'permits',
  },
  {
    clause: '8.2', title: 'Emergency preparedness and response',
    summary: 'Plan and periodically test emergency responses, provide first aid, train and inform everyone involved.',
    modules: [
      { label: 'Emergency Response (FERP contacts)', path: '/emergency-response' },
      { label: 'Mock Drills', path: '/mock-drills' },
      { label: 'Emergency Equipment', path: '/equipment' },
    ],
    keywords: ['emergency', 'drill', 'evacuation', 'fire', 'extinguisher', 'aed', 'first aid', 'preparedness', 'response', 'ferp', 'police', 'ambulance', 'escalation'],
    stat: 'emergency',
  },
  {
    clause: '9.1', title: 'Monitoring, measurement, analysis and evaluation',
    summary: 'Decide what to monitor and measure (incl. legal compliance), keep evidence, and evaluate OH&S performance.',
    modules: [{ label: 'Inspections', path: '/inspections' }, { label: 'Dashboards', path: '/dashboard' }],
    keywords: ['monitoring', 'measurement', 'inspection', 'checklist', 'evaluation of compliance'],
    stat: 'inspections',
  },
  {
    clause: '9.2', title: 'Internal audit',
    summary: 'Audit the management system at planned intervals with objective auditors, report results and fix nonconformities.',
    modules: [{ label: 'Internal Audit (plans, findings, CAPA)', path: '/audit' }],
    keywords: ['internal audit', 'audit', 'auditor', 'findings', 'nonconformity', 'nc', 'ofi'],
    stat: 'audits',
  },
  {
    clause: '9.3', title: 'Management review',
    summary: 'Top management periodically reviews the whole system — performance, incidents, audits, consultation — and decides improvements.',
    modules: [{ label: 'HSE Committee — Management Review meetings', path: '/committee' }],
    keywords: ['management review'],
    stat: 'consultations',
  },
  {
    clause: '10.2', title: 'Incident, nonconformity and corrective action',
    summary: 'React to incidents and nonconformities, investigate causes with worker participation, and take corrective action.',
    modules: [{ label: 'Incidents & Investigation', path: '/incidents' }, { label: 'Action Tracker', path: '/actions' }],
    keywords: ['incident', 'near miss', 'injury', 'illness', 'investigation', 'corrective action', 'capa', '5-why', 'fishbone'],
    stat: 'incidents',
  },
  {
    clause: '10.3', title: 'Continual improvement',
    summary: 'Keep improving the suitability, adequacy and effectiveness of the system using audit, incident and performance results.',
    modules: [{ label: 'Dashboards', path: '/dashboard' }, { label: 'Action Tracker', path: '/actions' }],
    keywords: ['continual improvement', 'improve'],
    stat: null,
  },
]

export const CLAUSE_BY_NUMBER = Object.fromEntries(ISO_CLAUSES.map((c) => [c.clause, c]))
